#!/usr/bin/env bun
// gen-sdk — SK-DOCS-003 slice a. TypeDoc → MDX into reference/sdk/.

import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, posix, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { Application, TSConfigReader } from "typedoc";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(DOCS_ROOT, "../..");
const SDK_ENTRY = join(REPO_ROOT, "packages/sdk/src/index.ts");
const SDK_TSCONFIG = join(REPO_ROOT, "packages/sdk/tsconfig.json");
const DOCS_CONTENT = join(DOCS_ROOT, "src/content/docs");
const OUT_DIR = join(DOCS_CONTENT, "reference/sdk");
const URL_BASE = `/${relative(DOCS_CONTENT, OUT_DIR).split(sep).join("/")}`;
const SDK_EDIT_URL = "https://github.com/nlqdb/nlqdb/edit/main/packages/sdk/src/index.ts";

const BANNER =
  "{/* generated by apps/docs/scripts/gen-sdk.ts from packages/sdk/src/**.ts — DO NOT EDIT */}";

async function main() {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const app = await Application.bootstrapWithPlugins(
    {
      entryPoints: [SDK_ENTRY],
      tsconfig: SDK_TSCONFIG,
      out: OUT_DIR,
      plugin: ["typedoc-plugin-markdown"],
      readme: "none",
      hideBreadcrumbs: true,
      hidePageHeader: true,
      fileExtension: ".mdx",
      entryFileName: "index.mdx",
      indexFormat: "table",
      parametersFormat: "table",
      propertiesFormat: "table",
      enumMembersFormat: "table",
      typeDeclarationFormat: "table",
      useCodeBlocks: true,
      expandObjects: false,
      mergeReadme: false,
      // packages/sdk/src/index.ts documents every export with `//` line comments, not `/** */`
      // JSDoc. Without "all" TypeDoc renders every Description column as `-`.
      commentStyle: "all",
    },
    [new TSConfigReader()],
  );

  const project = await app.convert();
  if (!project) {
    console.error("✗ gen-sdk: TypeDoc conversion failed");
    process.exit(1);
  }
  await app.generateOutputs(project);
  walkAndStamp(OUT_DIR);
  console.info(`✓ SDK reference → ${relative(REPO_ROOT, OUT_DIR)}`);
}

function walkAndStamp(dir: string): void {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) {
      walkAndStamp(p);
      continue;
    }
    if (!p.endsWith(".mdx") && !p.endsWith(".md")) continue;
    stampFile(p);
  }
}

// Lifts the H1 into Starlight's required `title` frontmatter; drops the H1 line so the page doesn't render two titles.
function stampFile(path: string): void {
  const raw = readFileSync(path, "utf8");
  if (raw.includes(BANNER)) return;
  const lines = raw.split("\n");
  let title = "API";
  let firstH1 = -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line === undefined) continue;
    if (line.startsWith("# ")) {
      title = line.slice(2).trim();
      firstH1 = i;
      break;
    }
    if (line.trim() !== "") break;
  }
  const body =
    firstH1 >= 0
      ? [...lines.slice(0, firstH1), ...lines.slice(firstH1 + 1)].join("\n").replace(/^\n+/, "")
      : raw.replace(/^\n+/, "");
  const sourceRel = relative(OUT_DIR, path).split(sep).join("/");
  // The package index's H1 is the bare package name; name the page for what it is.
  if (title === "@nlqdb/sdk") title = "@nlqdb/sdk reference";
  const frontmatter = [
    "---",
    `title: ${yamlQuoted(title)}`,
    `description: ${yamlQuoted(describe(title, body))}`,
    // "Edit page" must target the source — the generated .mdx is gitignored,
    // so Starlight's default edit link 404s on GitHub.
    `editUrl: ${SDK_EDIT_URL}`,
    "---",
  ].join("\n");
  writeFileSync(path, `${frontmatter}\n\n${BANNER}\n\n${rewriteLinks(body, sourceRel)}`);
}

const DESCRIPTION_MAX = 155;
const DESCRIPTION_MIN = 110;

// SERP meta description from the page's own doc comment — the first prose
// paragraph TypeDoc emits after the signature + "Defined in" lines — prefixed
// with what the symbol is, so a `<meta name="description">` never falls back to
// the site-wide default (60 identical descriptions in the 2026-09 Ahrefs audit).
function describe(title: string, body: string): string {
  const [kind, name] = title.includes(": ") ? title.split(": ", 2) : ["", title];
  const lead = `${name} (${kind.toLowerCase() || "module"}) in the @nlqdb/sdk TypeScript client`;
  const prose = body
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .find((p) => p && !/^(```|Defined in:|#|\||>|\{\/\*)/.test(p));
  const summary = prose
    ? plainText(prose)
    : "Generated from packages/sdk/src — every exported class, function, and type alias of the nlqdb client, with the source line each is defined on.";
  return clamp(`${lead}: ${summary}`, DESCRIPTION_MAX, DESCRIPTION_MIN);
}

function plainText(md: string): string {
  return md
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[`*_]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

// Word-boundary clamp to `max`; a short input is padded with the reference
// context sentence rather than shipped as a thin snippet.
function clamp(text: string, max: number, min: number): string {
  let t = text;
  if (t.length < min)
    t = `${t.replace(/[.\s]+$/, "")}. Part of the @nlqdb/sdk reference for nlqdb, a database you talk to.`;
  if (t.length <= max) return t;
  const cut = t.slice(0, max - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ")).replace(/[\s.,;:—–-]+$/, "")}…`;
}

// Absolute URLs: Starlight serves each non-index page at a trailing-slash URL, so resolving TypeDoc's filesystem-relative cross-refs against the rendered URL drops the parent directory and 404s every non-index cross-ref.
function rewriteLinks(body: string, sourceRelPath: string): string {
  const sourceDir = posix.dirname(sourceRelPath);
  return body.replace(/\]\(([^)#\s]+)\.mdx(#[^)]*)?\)/g, (match, linkPath: string, hash = "") => {
    if (/^(https?:|mailto:|\/)/.test(linkPath)) return match;
    const resolved = posix.normalize(posix.join(sourceDir, linkPath)).toLowerCase();
    return `](${URL_BASE}/${resolved}/${hash})`;
  });
}

// YAML double-quoted string escapes both `\` and `"`; covers anything TypeDoc emits as a title.
function yamlQuoted(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

await main();
