#!/usr/bin/env bun
// Generate the CLI reference page from `nlq help --json` (per SK-DOCS-003
// slice c). Output: `apps/docs/src/content/docs/cli.mdx`.
//
// Resolution order for the `nlq` binary:
//   1. $NLQDB_CLI       — explicit override (CI uses this).
//   2. cli/dist/nlq     — local build (`go -C cli build -o dist/nlq ./cmd/nlq`).
//   3. $PATH lookup     — for contributors with `nlq` installed.

import { existsSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(DOCS_ROOT, "../..");
const OUT = join(DOCS_ROOT, "src/content/docs/cli.mdx");

const BANNER =
  "{/* generated by apps/docs/scripts/gen-cli.ts from `nlq help --json` — DO NOT EDIT */}";

type FlagNode = {
  name: string;
  shorthand?: string;
  type: string;
  default?: string;
  usage: string;
  persistent?: boolean;
};

type CmdNode = {
  name: string;
  use?: string;
  path: string;
  short?: string;
  long?: string;
  example?: string;
  aliases?: string[];
  hidden?: boolean;
  flags?: FlagNode[];
  subcommands?: CmdNode[];
};

async function main() {
  const bin = await locateBinary();
  const proc = Bun.spawnSync({
    cmd: [bin, "help", "--json"],
    stdout: "pipe",
    stderr: "pipe",
  });
  if (proc.exitCode !== 0) {
    console.error(`✗ gen-cli: \`${bin} help --json\` exited ${proc.exitCode}`);
    console.error(proc.stderr.toString());
    process.exit(1);
  }
  const tree = JSON.parse(proc.stdout.toString()) as CmdNode;
  writeFileSync(OUT, render(tree));
  console.info(`✓ CLI reference → ${relative(REPO_ROOT, OUT)}`);
}

async function locateBinary(): Promise<string> {
  const fromEnv = process.env.NLQDB_CLI;
  if (fromEnv && existsSync(fromEnv)) return fromEnv;
  const fromDist = join(REPO_ROOT, "cli/dist/nlq");
  if (existsSync(fromDist) && statSync(fromDist).isFile()) return fromDist;
  // Last resort: rely on PATH. Bun.spawnSync resolves PATH automatically when
  // the cmd has no slash; using literal "nlq" lets it find a globally
  // installed binary.
  return "nlq";
}

function render(root: CmdNode): string {
  const description =
    root.short ??
    "nlqdb command-line tool — natural-language verbs (`ask`, `run`) plus database / key / MCP-install helpers.";

  const top = mdxSafeProse(root.long?.trim() || description);

  const sections: string[] = [];
  for (const sub of root.subcommands ?? []) {
    if (skip(sub)) continue;
    sections.push(renderCommand(sub, 2));
  }

  return [
    "---",
    `title: "nlq — CLI reference"`,
    `description: "${escapeYaml(description)}"`,
    "---",
    "",
    BANNER,
    "",
    top,
    "",
    renderFlags(root.flags ?? [], "## Global flags"),
    "## Commands",
    "",
    ...sections,
  ]
    .filter((s) => s !== "")
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .concat("\n");
}

function renderCommand(cmd: CmdNode, depth: number): string {
  const heading = "#".repeat(depth);
  const lines: string[] = [];
  lines.push(`${heading} ${cmd.path}`, "");
  if (cmd.short) lines.push(`_${mdxSafeProse(cmd.short)}_`, "");
  if (cmd.use) {
    const usage = cmd.path === cmd.name ? cmd.use : `${cmd.path} ${stripFirst(cmd.use)}`;
    lines.push("```bash", usage, "```", "");
  }
  if (cmd.long) lines.push(mdxSafeProse(cmd.long), "");
  if (cmd.aliases && cmd.aliases.length > 0) {
    lines.push(`**Aliases:** ${cmd.aliases.map((a) => `\`${a}\``).join(", ")}`, "");
  }
  if (cmd.flags && cmd.flags.length > 0) {
    lines.push(renderFlags(cmd.flags, `${heading}# Flags`));
  }
  if (cmd.example) {
    lines.push(`${heading}# Examples`, "", "```bash", cmd.example.trim(), "```", "");
  }
  for (const sub of cmd.subcommands ?? []) {
    if (skip(sub)) continue;
    lines.push(renderCommand(sub, depth + 1));
  }
  return lines.join("\n");
}

// Cobra auto-generates two subtrees we don't want in the docs:
//   • `completion` — shell-completion scripts; its Long text is raw bash
//     full of `<(` etc. that MDX would parse as JSX.
//   • Other `Hidden: true` commands marked at registration time.
function skip(cmd: CmdNode): boolean {
  if (cmd.hidden) return true;
  if (cmd.name === "completion") return true;
  return false;
}

// MDX 3 treats `<` and `{` as JSX/expression starters. We're rendering
// prose pulled from Go source, which can legitimately contain either —
// e.g. argument placeholders like `<goal>`. Escape both with a backslash
// so the prose renders as text. Code fences are not touched.
function mdxSafeProse(text: string): string {
  return text
    .split(/(```[\s\S]*?```|`[^`]*`)/g)
    .map((chunk, i) => (i % 2 === 0 ? chunk.replace(/[<{]/g, (m) => `\\${m}`) : chunk))
    .join("");
}

function renderFlags(flags: FlagNode[], heading: string): string {
  const local = flags.filter((f) => !f.persistent);
  const inherited = flags.filter((f) => f.persistent);
  if (local.length + inherited.length === 0) return "";

  const sections: string[] = [];
  if (local.length > 0) {
    sections.push(`${heading}`, "", flagTable(local), "");
  }
  if (inherited.length > 0) {
    sections.push(`${heading.replace(/Flags$/, "Inherited flags")}`, "", flagTable(inherited), "");
  }
  return sections.join("\n");
}

function flagTable(flags: FlagNode[]): string {
  const rows = flags.map((f) => {
    const flag = f.shorthand ? `\`-${f.shorthand}\`, \`--${f.name}\`` : `\`--${f.name}\``;
    const type = `\`${f.type}\``;
    const def = f.default && f.default !== "" && f.default !== "[]" ? `\`${f.default}\`` : "—";
    const usage = (f.usage ?? "").replace(/\|/g, "\\|");
    return `| ${flag} | ${type} | ${def} | ${usage} |`;
  });
  return ["| Flag | Type | Default | Description |", "| --- | --- | --- | --- |", ...rows].join(
    "\n",
  );
}

// Strip the first token (the verb / path component) from a Use string so
// nested headings render `nlq db ls [flags]` instead of `nlq db ls db ls`.
function stripFirst(use: string): string {
  const fields = use.split(/\s+/);
  return fields.slice(1).join(" ");
}

function escapeYaml(s: string): string {
  return s.replace(/"/g, '\\"').replace(/\s+/g, " ").trim();
}

await main();
