#!/usr/bin/env bun
// gen-sdk — SK-DOCS-003 slice a. TypeDoc → MDX into reference/sdk/.

import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { Application, TSConfigReader } from "typedoc";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(DOCS_ROOT, "../..");
const SDK_ENTRY = join(REPO_ROOT, "packages/sdk/src/index.ts");
const SDK_TSCONFIG = join(REPO_ROOT, "packages/sdk/tsconfig.json");
const OUT_DIR = join(DOCS_ROOT, "src/content/docs/reference/sdk");

const BANNER =
  "{/* generated by apps/docs/scripts/gen-sdk.ts from packages/sdk/src/**.ts — DO NOT EDIT */}";

async function main() {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const app = await Application.bootstrapWithPlugins(
    {
      entryPoints: [SDK_ENTRY],
      tsconfig: SDK_TSCONFIG,
      out: OUT_DIR,
      plugin: ["typedoc-plugin-markdown"],
      readme: "none",
      hideBreadcrumbs: true,
      hidePageHeader: true,
      fileExtension: ".mdx",
      entryFileName: "index.mdx",
      indexFormat: "table",
      parametersFormat: "table",
      propertiesFormat: "table",
      enumMembersFormat: "table",
      typeDeclarationFormat: "table",
      useCodeBlocks: true,
      expandObjects: false,
      mergeReadme: false,
    },
    [new TSConfigReader()],
  );

  const project = await app.convert();
  if (!project) {
    console.error("✗ gen-sdk: TypeDoc conversion failed");
    process.exit(1);
  }
  await app.generateOutputs(project);
  walkAndStamp(OUT_DIR);
  console.info(`✓ SDK reference → ${relative(REPO_ROOT, OUT_DIR)}`);
}

function walkAndStamp(dir: string): void {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) {
      walkAndStamp(p);
      continue;
    }
    if (!p.endsWith(".mdx") && !p.endsWith(".md")) continue;
    stampFile(p);
  }
}

// Lifts the H1 into Starlight's required `title` frontmatter; drops the H1 line so the page doesn't render two titles.
function stampFile(path: string): void {
  const raw = readFileSync(path, "utf8");
  if (raw.includes(BANNER)) return;
  const lines = raw.split("\n");
  let title = "API";
  let firstH1 = -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line === undefined) continue;
    if (line.startsWith("# ")) {
      title = line.slice(2).trim();
      firstH1 = i;
      break;
    }
    if (line.trim() !== "") break;
  }
  const body =
    firstH1 >= 0
      ? [...lines.slice(0, firstH1), ...lines.slice(firstH1 + 1)].join("\n").replace(/^\n+/, "")
      : raw.replace(/^\n+/, "");
  const next = `---\ntitle: ${yamlQuoted(title)}\n---\n\n${BANNER}\n\n${body}`;
  writeFileSync(path, next);
}

// YAML double-quoted string escapes both `\` and `"`; covers anything TypeDoc emits as a title.
function yamlQuoted(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

await main();
