#!/usr/bin/env bun
// gen-cli — SK-DOCS-003 slice c. Generates `cli.mdx` from `nlq help --json`.
// Binary resolution: $NLQDB_CLI → cli/dist/nlq → $PATH. CI (NLQDB_CLI set)
// fails hard if the binary doesn't run; local dev falls back to a placeholder
// page so `bun run dev` works without a Go toolchain.

import { existsSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(DOCS_ROOT, "../..");
const OUT = join(DOCS_ROOT, "src/content/docs/cli.mdx");

const BANNER =
  "{/* generated by apps/docs/scripts/gen-cli.ts from `nlq help --json` — DO NOT EDIT */}";

type FlagNode = {
  name: string;
  shorthand?: string;
  type: string;
  default?: string;
  usage: string;
  persistent?: boolean;
};

type CmdNode = {
  name: string;
  use?: string;
  path: string;
  short?: string;
  long?: string;
  example?: string;
  aliases?: string[];
  hidden?: boolean;
  flags?: FlagNode[];
  subcommands?: CmdNode[];
};

async function main() {
  const bin = locateBinary();
  if (!bin) {
    writeFileSync(OUT, placeholder());
    console.warn(
      `! gen-cli: \`nlq\` binary not found (set NLQDB_CLI or build cli/dist/nlq); wrote placeholder`,
    );
    return;
  }
  const proc = Bun.spawnSync({ cmd: [bin, "help", "--json"], stdout: "pipe", stderr: "pipe" });
  if (proc.exitCode !== 0) {
    if (process.env.NLQDB_CLI || process.env.CI) {
      console.error(`✗ gen-cli: \`${bin} help --json\` exited ${proc.exitCode}`);
      console.error(proc.stderr.toString());
      process.exit(1);
    }
    writeFileSync(OUT, placeholder());
    console.warn(`! gen-cli: \`${bin} help --json\` failed; wrote placeholder`);
    return;
  }
  const tree = JSON.parse(proc.stdout.toString()) as CmdNode;
  writeFileSync(OUT, render(tree));
  console.info(`✓ CLI reference → ${relative(REPO_ROOT, OUT)}`);
}

function locateBinary(): string | null {
  const fromEnv = process.env.NLQDB_CLI;
  if (fromEnv) return existsSync(fromEnv) ? fromEnv : null;
  const fromDist = join(REPO_ROOT, "cli/dist/nlq");
  if (existsSync(fromDist) && statSync(fromDist).isFile()) return fromDist;
  return null;
}

function placeholder(): string {
  return [
    "---",
    `title: "nlq — CLI reference"`,
    `description: "nlqdb command-line tool. Generated from \`nlq help --json\`."`,
    "---",
    "",
    BANNER,
    "",
    "Build the CLI binary (`go -C cli build -o dist/nlq ./cmd/nlq`) and re-run",
    "`bun run --filter apps/docs gen` to regenerate this page from the live",
    "`nlq help --json` output.",
    "",
  ].join("\n");
}

function render(root: CmdNode): string {
  const description =
    root.short ??
    "nlqdb command-line tool — natural-language verbs (`ask`, `run`) plus database / key / MCP-install helpers.";

  const top = mdxSafeProse(root.long?.trim() || description);

  const sections: string[] = [];
  for (const sub of root.subcommands ?? []) {
    if (skip(sub)) continue;
    sections.push(renderCommand(sub, 2));
  }

  return [
    "---",
    `title: "nlq — CLI reference"`,
    `description: "${escapeYaml(description)}"`,
    "---",
    "",
    BANNER,
    "",
    top,
    "",
    renderFlags(root.flags ?? [], "## Global flags"),
    "## Commands",
    "",
    ...sections,
  ]
    .filter((s) => s !== "")
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .concat("\n");
}

function renderCommand(cmd: CmdNode, depth: number): string {
  const heading = "#".repeat(depth);
  const lines: string[] = [];
  lines.push(`${heading} ${cmd.path}`, "");
  if (cmd.short) lines.push(`_${mdxSafeProse(cmd.short)}_`, "");
  if (cmd.use) {
    const usage = cmd.path === cmd.name ? cmd.use : `${cmd.path} ${stripFirst(cmd.use)}`;
    lines.push("```bash", usage, "```", "");
  }
  if (cmd.long) lines.push(mdxSafeProse(cmd.long), "");
  if (cmd.aliases && cmd.aliases.length > 0) {
    lines.push(`**Aliases:** ${cmd.aliases.map((a) => `\`${a}\``).join(", ")}`, "");
  }
  if (cmd.flags && cmd.flags.length > 0) {
    lines.push(renderFlags(cmd.flags, `${heading}# Flags`));
  }
  if (cmd.example) {
    lines.push(`${heading}# Examples`, "", "```bash", cmd.example.trim(), "```", "");
  }
  for (const sub of cmd.subcommands ?? []) {
    if (skip(sub)) continue;
    lines.push(renderCommand(sub, depth + 1));
  }
  return lines.join("\n");
}

// Cobra's auto-generated `completion` subtree has raw-bash Long text with `<(` that MDX would parse as JSX.
function skip(cmd: CmdNode): boolean {
  if (cmd.hidden) return true;
  if (cmd.name === "completion") return true;
  return false;
}

// MDX treats `<` / `{` as JSX/expression starters; escape them in prose so argument placeholders like `<goal>` render as text. Code fences are left alone.
function mdxSafeProse(text: string): string {
  return text
    .split(/(```[\s\S]*?```|`[^`]*`)/g)
    .map((chunk, i) => (i % 2 === 0 ? chunk.replace(/[<{]/g, (m) => `\\${m}`) : chunk))
    .join("");
}

function renderFlags(flags: FlagNode[], heading: string): string {
  const local = flags.filter((f) => !f.persistent);
  const inherited = flags.filter((f) => f.persistent);
  if (local.length + inherited.length === 0) return "";

  const sections: string[] = [];
  if (local.length > 0) {
    sections.push(`${heading}`, "", flagTable(local), "");
  }
  if (inherited.length > 0) {
    sections.push(`${heading.replace(/Flags$/, "Inherited flags")}`, "", flagTable(inherited), "");
  }
  return sections.join("\n");
}

function flagTable(flags: FlagNode[]): string {
  const rows = flags.map((f) => {
    const flag = f.shorthand ? `\`-${f.shorthand}\`, \`--${f.name}\`` : `\`--${f.name}\``;
    const type = `\`${f.type}\``;
    const def = f.default && f.default !== "" && f.default !== "[]" ? `\`${f.default}\`` : "—";
    const usage = (f.usage ?? "").replace(/\|/g, "\\|");
    return `| ${flag} | ${type} | ${def} | ${usage} |`;
  });
  return ["| Flag | Type | Default | Description |", "| --- | --- | --- | --- |", ...rows].join(
    "\n",
  );
}

// Drop Cobra's `Use` first token (the verb itself) so nested headings render `nlq db ls [flags]`, not `nlq db ls db ls`.
function stripFirst(use: string): string {
  const fields = use.split(/\s+/);
  return fields.slice(1).join(" ");
}

function escapeYaml(s: string): string {
  return s.replace(/"/g, '\\"').replace(/\s+/g, " ").trim();
}

await main();
