#!/usr/bin/env bun
// gen-examples — SK-DOCS-003 slice b. examples/<name>/README.md → tutorials/<name>.mdx.

import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = join(SCRIPT_DIR, "..");
const REPO_ROOT = join(DOCS_ROOT, "../..");
const EXAMPLES_DIR = join(REPO_ROOT, "examples");
const OUT_DIR = join(DOCS_ROOT, "src/content/docs/tutorials");

const GITHUB_BASE = "https://github.com/nlqdb/nlqdb/tree/main";
const GITHUB_BLOB = "https://github.com/nlqdb/nlqdb/blob/main";

// Slug-to-sidebar-label override; falls back to the README's H1 when absent.
const TITLE_OVERRIDES: Record<string, string> = {
  html: "Plain HTML",
  cli: "CLI",
  curl: "curl",
  react: "React",
  nextjs: "Next.js",
  vue: "Vue",
  nuxt: "Nuxt",
  svelte: "Svelte",
  sveltekit: "SvelteKit",
  astro: "Astro",
  solid: "SolidJS",
};

// Emitted as the `sidebar.order` frontmatter field so Starlight doesn't sort alphabetically (html first, react second, …).
const SIDEBAR_ORDER: Record<string, number> = {
  html: 1,
  react: 2,
  nextjs: 3,
  vue: 4,
  nuxt: 5,
  svelte: 6,
  sveltekit: 7,
  astro: 8,
  solid: 9,
  cli: 10,
  curl: 11,
};

const BANNER_TEMPLATE = (name: string) =>
  `{/* generated by apps/docs/scripts/gen-examples.ts from examples/${name}/ — DO NOT EDIT */}`;

function main(): void {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const slugs = readdirSync(EXAMPLES_DIR).filter((name) => {
    const p = join(EXAMPLES_DIR, name);
    return statSync(p).isDirectory();
  });

  let count = 0;
  for (const slug of slugs.sort()) {
    const readme = join(EXAMPLES_DIR, slug, "README.md");
    try {
      statSync(readme);
    } catch {
      console.warn(`! examples/${slug}: missing README.md — skipping`);
      continue;
    }
    const body = readFileSync(readme, "utf8");
    writeFileSync(join(OUT_DIR, `${slug}.mdx`), renderTutorial(slug, body));
    count++;
  }

  console.info(`✓ Tutorials → ${relative(REPO_ROOT, OUT_DIR)} (${count} pages)`);
}

function renderTutorial(slug: string, source: string): string {
  const lines = source.split("\n");
  let h1 = TITLE_OVERRIDES[slug] ?? slug;
  let h1Index = -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line === undefined) continue;
    if (line.startsWith("# ")) {
      h1 = TITLE_OVERRIDES[slug] ?? line.slice(2).trim();
      h1Index = i;
      break;
    }
  }

  let description = "";
  if (h1Index >= 0) {
    for (let i = h1Index + 1; i < lines.length; i++) {
      const line = lines[i];
      if (line === undefined) continue;
      const t = line.trim();
      if (!t) continue;
      if (t.startsWith("#")) break;
      description = collapse(stripMarkdown(t));
      break;
    }
  }

  const bodyLines = h1Index >= 0 ? lines.slice(h1Index + 1) : lines;
  const rewritten = rewriteRelativeLinks(bodyLines.join("\n"), slug).replace(/^\n+/, "");

  const order = SIDEBAR_ORDER[slug];
  const frontmatter: string[] = ["---", `title: "${h1.replace(/"/g, '\\"')}"`];
  if (description) frontmatter.push(`description: "${description.replace(/"/g, '\\"')}"`);
  if (order !== undefined) {
    frontmatter.push("sidebar:");
    frontmatter.push(`  order: ${order}`);
  }
  frontmatter.push("---", "");

  const footer = [
    "",
    "## Live code",
    "",
    `Source on GitHub: [\`examples/${slug}/\`](${GITHUB_BASE}/examples/${slug}).`,
  ].join("\n");

  return `${frontmatter.join("\n")}${BANNER_TEMPLATE(slug)}\n\n${rewritten}\n${footer}\n`;
}

// Relative repo links don't resolve on docs.nlqdb.com — rewrite them to GitHub absolute URLs.
function rewriteRelativeLinks(body: string, slug: string): string {
  return body.replace(/\[([^\]]+)\]\(([^)]+)\)/g, (match, text: string, href: string) => {
    if (/^(https?:|mailto:|#|\/)/.test(href)) return match;
    if (href.startsWith("./") || href.startsWith("../")) {
      const target = resolveRelativeFromExample(slug, href);
      return `[${text}](${target})`;
    }
    return match;
  });
}

function resolveRelativeFromExample(slug: string, href: string): string {
  const segments: string[] = ["examples", slug];
  for (const part of href.split("/")) {
    if (part === "" || part === ".") continue;
    if (part === "..") segments.pop();
    else segments.push(part);
  }
  const last = segments[segments.length - 1];
  const isFile = last !== undefined && /\.[a-z0-9]+$/i.test(last);
  const prefix = isFile ? GITHUB_BLOB : GITHUB_BASE;
  return `${prefix}/${segments.join("/")}`;
}

function stripMarkdown(s: string): string {
  return s
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/[*_]+/g, "");
}

function collapse(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

main();
